apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  schedulerName: mikischeduler  # Specify the scheduler you want to use
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

